### ISSUE TITLE
Need to list user expertise topics

### ISSUE THREAD

**Issue by ingcoders** [JackOMG/lucyp#2]
![image](https://user-images.githubusercontent.com/33113218/32830309-08b97ea8-c9f5-11e7-994a-2da9ead54d6f.png)

Need to insert the expertise topics that the bot has learned about the user.

**Comment by Beuntj** [comment]
This has now been done and looks as follows. Guess we need to allow user to delete or add areas of expertise. Not sure how to best do that. Lets discuss.

![image](https://user-images.githubusercontent.com/33692725/32941491-e1f9ef3e-cb7d-11e7-93dc-726f80bb5c24.png)
